import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./lib/config";
import "./globals.css";
import Header from "./components/header";
import { serverFetch } from "./api/server-fetch";
import { CurrentUser } from "./auth/signup/types";
import { ApiUsers } from "./api/routes";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const result = await serverFetch<CurrentUser>({
    url: ApiUsers.CurrentUser,
    fallbackMessage: 'Failed to retrieve current user',
  });

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header currentUser={result.ok && result?.data?.currentUser ? result?.data?.currentUser : null} />
        {children}
      </body>
    </html>
  );
}
